version: '3.4'

networks:
  chatapplication:

services:
  chatappdb:
    container_name: chatappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
      - chatapplication
  chatappbackend:
    image: chatappbackend
    build:
      context: .
      dockerfile: ChatAppBackend/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - chatappdb
    environment:
      - DB_HOST=chatappdb
      - DB_NAME=ChatAppDatabase
      - DB_SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
      - chatapplication