version: '3.4'

networks:
  chatapplication:

services:
  chatappfrontend:
    container_name: chatappfrontend
    image: chatappfrontend
    build: ./client/chat-app-frontend
    ports:
      - 3000:3000
    volumes:
      - ./client/chat-app-frontend:/app
    stdin_open: true
    tty: true
    networks:
      - chatapplication
  chatappdb:
    container_name: chatappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
      - chatapplication
  chatappbackend:
    image: chatappbackend
    build:
      context: .
      dockerfile: server/ChatAppBackend/ChatAppBackend/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - chatappdb
    environment:
      - DB_HOST=chatappdb
      - DB_NAME=ChatAppDatabase
      - DB_SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
      - chatapplication